-- Generate a warning icon sprite for an entity and return it (caller needs to save it!)
function create_warning_icon(entity)
    -- TODO: Try to animate (blinking warning sprite)?
    -- TODO: Custom icon
    return rendering.draw_sprite {
        target = entity,
        surface = entity.surface,
        sprite = "utility.danger_icon",
        render_layer = "entity-info-icon-above",
        x_scale = 0.5,
        y_scale = 0.5,
    }
end

-- Generate an acknowledged icon sprite for an entity and return it (caller needs to save it!)
function create_acknowledged_icon(entity)
    -- TODO: Custom icon
    return rendering.draw_sprite {
        target = entity,
        surface = entity.surface,
        sprite = "utility.check_mark_green",
        render_layer = "entity-info-icon-above",
        x_scale = 1,
        y_scale = 1,
    }
end

-- Clear any icon sprite from an entity (if it has one)
function clear_entity_icon_sprite(entity)
    if storage.entity_icon_sprites[entity.unit_number] ~= nil then
        storage.entity_icon_sprites[entity.unit_number].destroy()
        storage.entity_icon_sprites[entity.unit_number] = nil
    end
end

-- Destroys all sprites generated by this mod and clears the list of sprites
function clear_all_sprites()
    -- Clear all render objects created by this mod
    rendering.clear(script.mod_name)

    -- Clear list of sprites
    storage.entity_icon_sprites = {}
end
